### ISSUE TITLE
Have the model checkpoint?

### ISSUE THREAD

**Issue by dengxiongshi** [hxwxss/SimpleFusion-A-Simple-Fusion-Framework-for-Infrared-and-Visible-Images#1]

**Comment by MingChen0831** [comment]
yes, we have just submitted the relevant files.

**Comment by hxwxss** [comment]
You can also easily get the model checkpoint in this link: https://drive.google.com/file/d/1SI45t38YWUDTeUHpBrx1kpexNRSvRbsK/view?usp=sharing
If you have any questions, don't hesitate to contact me by email: hanxuanwxss@gmail.com.

**Comment by dengxiongshi** [comment]
> You can also easily get the model checkpoint in this link: https://drive.google.com/file/d/1SI45t38YWUDTeUHpBrx1kpexNRSvRbsK/view?usp=sharing If you have any questions, don't hesitate to contact me by email: [hanxuanwxss@gmail.com](mailto:hanxuanwxss@gmail.com).

@hxwxss Thank you!
