### ISSUE TITLE
About the great_NET parameter?

### ISSUE THREAD

**Issue by dengxiongshi** [hxwxss/SimpleFusion-A-Simple-Fusion-Framework-for-Infrared-and-Visible-Images#2]
@hxwxss Hello! I found the num parameter not used in great_NET function. Can you explain why have the num parameter?

**Comment by dengxiongshi** [comment]
@hxwxss I found the checkpoint model is trained by one channel image. Have three channels image checkpoint model?

**Comment by MingChen0831** [comment]
We apologize, there is indeed a parameter in the function that has not been used. We will refactor the project code and open source it later. All of our experimental data is based on a single channel, which is also a very common practice for this task.

**Comment by dengxiongshi** [comment]
> We apologize, there is indeed a parameter in the function that has not been used. We will refactor the project code and open source it later. All of our experimental data is based on a single channel, which is also a very common practice for this task.

@MingChen0831 😄🤭
